# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: geocube/pb/datasetMeta.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from geocube.pb import dataformat_pb2 as geocube_dot_pb_dot_dataformat__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1cgeocube/pb/datasetMeta.proto\x12\x07geocube\x1a\x1bgeocube/pb/dataformat.proto\";\n\x0b\x44\x61tasetMeta\x12,\n\rinternalsMeta\x18\x03 \x03(\x0b\x32\x15.geocube.InternalMeta\"\xac\x01\n\x0cInternalMeta\x12\x15\n\rcontainer_uri\x18\x01 \x01(\t\x12\x18\n\x10\x63ontainer_subdir\x18\x02 \x01(\t\x12\r\n\x05\x62\x61nds\x18\x03 \x03(\x03\x12$\n\x07\x64\x66ormat\x18\x04 \x01(\x0b\x32\x13.geocube.DataFormat\x12\x11\n\trange_min\x18\x05 \x01(\x01\x12\x11\n\trange_max\x18\x06 \x01(\x01\x12\x10\n\x08\x65xponent\x18\x07 \x01(\x01\x42\x0eZ\x0c./pb;geocubeb\x06proto3')



_DATASETMETA = DESCRIPTOR.message_types_by_name['DatasetMeta']
_INTERNALMETA = DESCRIPTOR.message_types_by_name['InternalMeta']
DatasetMeta = _reflection.GeneratedProtocolMessageType('DatasetMeta', (_message.Message,), {
  'DESCRIPTOR' : _DATASETMETA,
  '__module__' : 'geocube.pb.datasetMeta_pb2'
  # @@protoc_insertion_point(class_scope:geocube.DatasetMeta)
  })
_sym_db.RegisterMessage(DatasetMeta)

InternalMeta = _reflection.GeneratedProtocolMessageType('InternalMeta', (_message.Message,), {
  'DESCRIPTOR' : _INTERNALMETA,
  '__module__' : 'geocube.pb.datasetMeta_pb2'
  # @@protoc_insertion_point(class_scope:geocube.InternalMeta)
  })
_sym_db.RegisterMessage(InternalMeta)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z\014./pb;geocube'
  _DATASETMETA._serialized_start=70
  _DATASETMETA._serialized_end=129
  _INTERNALMETA._serialized_start=132
  _INTERNALMETA._serialized_end=304
# @@protoc_insertion_point(module_scope)
