# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: geocube/pb/dataformat.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1bgeocube/pb/dataformat.proto\x12\x07geocube\"\xe7\x01\n\nDataFormat\x12(\n\x05\x64type\x18\x01 \x01(\x0e\x32\x19.geocube.DataFormat.Dtype\x12\x0f\n\x07no_data\x18\x02 \x01(\x01\x12\x11\n\tmin_value\x18\x03 \x01(\x01\x12\x11\n\tmax_value\x18\x04 \x01(\x01\"x\n\x05\x44type\x12\r\n\tUNDEFINED\x10\x00\x12\t\n\x05UInt8\x10\x01\x12\n\n\x06UInt16\x10\x02\x12\n\n\x06UInt32\x10\x03\x12\t\n\x05Int16\x10\x05\x12\t\n\x05Int32\x10\x06\x12\x0b\n\x07\x46loat32\x10\x07\x12\x0b\n\x07\x46loat64\x10\x08\x12\r\n\tComplex64\x10\tB\x0eZ\x0c./pb;geocubeb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'geocube.pb.dataformat_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\014./pb;geocube'
  _globals['_DATAFORMAT']._serialized_start=41
  _globals['_DATAFORMAT']._serialized_end=272
  _globals['_DATAFORMAT_DTYPE']._serialized_start=152
  _globals['_DATAFORMAT_DTYPE']._serialized_end=272
# @@protoc_insertion_point(module_scope)
