# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from geocube.pb import catalog_pb2 as geocube_dot_pb_dot_catalog__pb2
from geocube.pb import geocube_pb2 as geocube_dot_pb_dot_geocube__pb2
from geocube.pb import layouts_pb2 as geocube_dot_pb_dot_layouts__pb2
from geocube.pb import operations_pb2 as geocube_dot_pb_dot_operations__pb2
from geocube.pb import records_pb2 as geocube_dot_pb_dot_records__pb2
from geocube.pb import variables_pb2 as geocube_dot_pb_dot_variables__pb2


class GeocubeStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ListRecords = channel.unary_stream(
                '/geocube.Geocube/ListRecords',
                request_serializer=geocube_dot_pb_dot_records__pb2.ListRecordsRequest.SerializeToString,
                response_deserializer=geocube_dot_pb_dot_records__pb2.ListRecordsResponseItem.FromString,
                )
        self.CreateRecords = channel.unary_unary(
                '/geocube.Geocube/CreateRecords',
                request_serializer=geocube_dot_pb_dot_records__pb2.CreateRecordsRequest.SerializeToString,
                response_deserializer=geocube_dot_pb_dot_records__pb2.CreateRecordsResponse.FromString,
                )
        self.DeleteRecords = channel.unary_unary(
                '/geocube.Geocube/DeleteRecords',
                request_serializer=geocube_dot_pb_dot_records__pb2.DeleteRecordsRequest.SerializeToString,
                response_deserializer=geocube_dot_pb_dot_records__pb2.DeleteRecordsResponse.FromString,
                )
        self.AddRecordsTags = channel.unary_unary(
                '/geocube.Geocube/AddRecordsTags',
                request_serializer=geocube_dot_pb_dot_records__pb2.AddRecordsTagsRequest.SerializeToString,
                response_deserializer=geocube_dot_pb_dot_records__pb2.AddRecordsTagsResponse.FromString,
                )
        self.RemoveRecordsTags = channel.unary_unary(
                '/geocube.Geocube/RemoveRecordsTags',
                request_serializer=geocube_dot_pb_dot_records__pb2.RemoveRecordsTagsRequest.SerializeToString,
                response_deserializer=geocube_dot_pb_dot_records__pb2.RemoveRecordsTagsResponse.FromString,
                )
        self.CreateAOI = channel.unary_unary(
                '/geocube.Geocube/CreateAOI',
                request_serializer=geocube_dot_pb_dot_records__pb2.CreateAOIRequest.SerializeToString,
                response_deserializer=geocube_dot_pb_dot_records__pb2.CreateAOIResponse.FromString,
                )
        self.GetAOI = channel.unary_unary(
                '/geocube.Geocube/GetAOI',
                request_serializer=geocube_dot_pb_dot_records__pb2.GetAOIRequest.SerializeToString,
                response_deserializer=geocube_dot_pb_dot_records__pb2.GetAOIResponse.FromString,
                )
        self.CreateVariable = channel.unary_unary(
                '/geocube.Geocube/CreateVariable',
                request_serializer=geocube_dot_pb_dot_variables__pb2.CreateVariableRequest.SerializeToString,
                response_deserializer=geocube_dot_pb_dot_variables__pb2.CreateVariableResponse.FromString,
                )
        self.InstantiateVariable = channel.unary_unary(
                '/geocube.Geocube/InstantiateVariable',
                request_serializer=geocube_dot_pb_dot_variables__pb2.InstantiateVariableRequest.SerializeToString,
                response_deserializer=geocube_dot_pb_dot_variables__pb2.InstantiateVariableResponse.FromString,
                )
        self.GetVariable = channel.unary_unary(
                '/geocube.Geocube/GetVariable',
                request_serializer=geocube_dot_pb_dot_variables__pb2.GetVariableRequest.SerializeToString,
                response_deserializer=geocube_dot_pb_dot_variables__pb2.GetVariableResponse.FromString,
                )
        self.ListVariables = channel.unary_stream(
                '/geocube.Geocube/ListVariables',
                request_serializer=geocube_dot_pb_dot_variables__pb2.ListVariablesRequest.SerializeToString,
                response_deserializer=geocube_dot_pb_dot_variables__pb2.ListVariablesResponseItem.FromString,
                )
        self.UpdateVariable = channel.unary_unary(
                '/geocube.Geocube/UpdateVariable',
                request_serializer=geocube_dot_pb_dot_variables__pb2.UpdateVariableRequest.SerializeToString,
                response_deserializer=geocube_dot_pb_dot_variables__pb2.UpdateVariableResponse.FromString,
                )
        self.UpdateInstance = channel.unary_unary(
                '/geocube.Geocube/UpdateInstance',
                request_serializer=geocube_dot_pb_dot_variables__pb2.UpdateInstanceRequest.SerializeToString,
                response_deserializer=geocube_dot_pb_dot_variables__pb2.UpdateInstanceResponse.FromString,
                )
        self.DeleteVariable = channel.unary_unary(
                '/geocube.Geocube/DeleteVariable',
                request_serializer=geocube_dot_pb_dot_variables__pb2.DeleteVariableRequest.SerializeToString,
                response_deserializer=geocube_dot_pb_dot_variables__pb2.DeleteVariableResponse.FromString,
                )
        self.DeleteInstance = channel.unary_unary(
                '/geocube.Geocube/DeleteInstance',
                request_serializer=geocube_dot_pb_dot_variables__pb2.DeleteInstanceRequest.SerializeToString,
                response_deserializer=geocube_dot_pb_dot_variables__pb2.DeleteInstanceResponse.FromString,
                )
        self.CreatePalette = channel.unary_unary(
                '/geocube.Geocube/CreatePalette',
                request_serializer=geocube_dot_pb_dot_variables__pb2.CreatePaletteRequest.SerializeToString,
                response_deserializer=geocube_dot_pb_dot_variables__pb2.CreatePaletteResponse.FromString,
                )
        self.IndexDatasets = channel.unary_unary(
                '/geocube.Geocube/IndexDatasets',
                request_serializer=geocube_dot_pb_dot_operations__pb2.IndexDatasetsRequest.SerializeToString,
                response_deserializer=geocube_dot_pb_dot_operations__pb2.IndexDatasetsResponse.FromString,
                )
        self.IngestDatasets = channel.unary_stream(
                '/geocube.Geocube/IngestDatasets',
                request_serializer=geocube_dot_pb_dot_operations__pb2.IngestDatasetsRequest.SerializeToString,
                response_deserializer=geocube_dot_pb_dot_operations__pb2.IngestDatasetsResponse.FromString,
                )
        self.ConfigConsolidation = channel.unary_unary(
                '/geocube.Geocube/ConfigConsolidation',
                request_serializer=geocube_dot_pb_dot_operations__pb2.ConfigConsolidationRequest.SerializeToString,
                response_deserializer=geocube_dot_pb_dot_operations__pb2.ConfigConsolidationResponse.FromString,
                )
        self.Consolidate = channel.unary_unary(
                '/geocube.Geocube/Consolidate',
                request_serializer=geocube_dot_pb_dot_operations__pb2.ConsolidateRequest.SerializeToString,
                response_deserializer=geocube_dot_pb_dot_operations__pb2.ConsolidateResponse.FromString,
                )
        self.GetJob = channel.unary_unary(
                '/geocube.Geocube/GetJob',
                request_serializer=geocube_dot_pb_dot_operations__pb2.GetJobRequest.SerializeToString,
                response_deserializer=geocube_dot_pb_dot_operations__pb2.GetJobResponse.FromString,
                )
        self.CleanJobs = channel.unary_unary(
                '/geocube.Geocube/CleanJobs',
                request_serializer=geocube_dot_pb_dot_operations__pb2.CleanJobsRequest.SerializeToString,
                response_deserializer=geocube_dot_pb_dot_operations__pb2.CleanJobsResponse.FromString,
                )
        self.RetryJob = channel.unary_unary(
                '/geocube.Geocube/RetryJob',
                request_serializer=geocube_dot_pb_dot_operations__pb2.RetryJobRequest.SerializeToString,
                response_deserializer=geocube_dot_pb_dot_operations__pb2.RetryJobResponse.FromString,
                )
        self.CancelJob = channel.unary_unary(
                '/geocube.Geocube/CancelJob',
                request_serializer=geocube_dot_pb_dot_operations__pb2.CancelJobRequest.SerializeToString,
                response_deserializer=geocube_dot_pb_dot_operations__pb2.CancelJobResponse.FromString,
                )
        self.GetCube = channel.unary_stream(
                '/geocube.Geocube/GetCube',
                request_serializer=geocube_dot_pb_dot_catalog__pb2.GetCubeRequest.SerializeToString,
                response_deserializer=geocube_dot_pb_dot_catalog__pb2.GetCubeResponse.FromString,
                )
        self.GetXYZTile = channel.unary_unary(
                '/geocube.Geocube/GetXYZTile',
                request_serializer=geocube_dot_pb_dot_catalog__pb2.GetTileRequest.SerializeToString,
                response_deserializer=geocube_dot_pb_dot_catalog__pb2.GetTileResponse.FromString,
                )
        self.CreateLayout = channel.unary_unary(
                '/geocube.Geocube/CreateLayout',
                request_serializer=geocube_dot_pb_dot_layouts__pb2.CreateLayoutRequest.SerializeToString,
                response_deserializer=geocube_dot_pb_dot_layouts__pb2.CreateLayoutResponse.FromString,
                )
        self.TileAOI = channel.unary_stream(
                '/geocube.Geocube/TileAOI',
                request_serializer=geocube_dot_pb_dot_layouts__pb2.TileAOIRequest.SerializeToString,
                response_deserializer=geocube_dot_pb_dot_layouts__pb2.TileAOIResponse.FromString,
                )
        self.Version = channel.unary_unary(
                '/geocube.Geocube/Version',
                request_serializer=geocube_dot_pb_dot_geocube__pb2.GetVersionRequest.SerializeToString,
                response_deserializer=geocube_dot_pb_dot_geocube__pb2.GetVersionResponse.FromString,
                )


class GeocubeServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ListRecords(self, request, context):
        """Records
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateRecords(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteRecords(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AddRecordsTags(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RemoveRecordsTags(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateAOI(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAOI(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateVariable(self, request, context):
        """Variables
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def InstantiateVariable(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetVariable(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListVariables(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateVariable(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateInstance(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteVariable(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteInstance(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreatePalette(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def IndexDatasets(self, request, context):
        """Operations
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def IngestDatasets(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ConfigConsolidation(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Consolidate(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetJob(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CleanJobs(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RetryJob(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CancelJob(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetCube(self, request, context):
        """Catalog
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetXYZTile(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateLayout(self, request, context):
        """Layout
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def TileAOI(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Version(self, request, context):
        """Version
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GeocubeServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ListRecords': grpc.unary_stream_rpc_method_handler(
                    servicer.ListRecords,
                    request_deserializer=geocube_dot_pb_dot_records__pb2.ListRecordsRequest.FromString,
                    response_serializer=geocube_dot_pb_dot_records__pb2.ListRecordsResponseItem.SerializeToString,
            ),
            'CreateRecords': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateRecords,
                    request_deserializer=geocube_dot_pb_dot_records__pb2.CreateRecordsRequest.FromString,
                    response_serializer=geocube_dot_pb_dot_records__pb2.CreateRecordsResponse.SerializeToString,
            ),
            'DeleteRecords': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteRecords,
                    request_deserializer=geocube_dot_pb_dot_records__pb2.DeleteRecordsRequest.FromString,
                    response_serializer=geocube_dot_pb_dot_records__pb2.DeleteRecordsResponse.SerializeToString,
            ),
            'AddRecordsTags': grpc.unary_unary_rpc_method_handler(
                    servicer.AddRecordsTags,
                    request_deserializer=geocube_dot_pb_dot_records__pb2.AddRecordsTagsRequest.FromString,
                    response_serializer=geocube_dot_pb_dot_records__pb2.AddRecordsTagsResponse.SerializeToString,
            ),
            'RemoveRecordsTags': grpc.unary_unary_rpc_method_handler(
                    servicer.RemoveRecordsTags,
                    request_deserializer=geocube_dot_pb_dot_records__pb2.RemoveRecordsTagsRequest.FromString,
                    response_serializer=geocube_dot_pb_dot_records__pb2.RemoveRecordsTagsResponse.SerializeToString,
            ),
            'CreateAOI': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateAOI,
                    request_deserializer=geocube_dot_pb_dot_records__pb2.CreateAOIRequest.FromString,
                    response_serializer=geocube_dot_pb_dot_records__pb2.CreateAOIResponse.SerializeToString,
            ),
            'GetAOI': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAOI,
                    request_deserializer=geocube_dot_pb_dot_records__pb2.GetAOIRequest.FromString,
                    response_serializer=geocube_dot_pb_dot_records__pb2.GetAOIResponse.SerializeToString,
            ),
            'CreateVariable': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateVariable,
                    request_deserializer=geocube_dot_pb_dot_variables__pb2.CreateVariableRequest.FromString,
                    response_serializer=geocube_dot_pb_dot_variables__pb2.CreateVariableResponse.SerializeToString,
            ),
            'InstantiateVariable': grpc.unary_unary_rpc_method_handler(
                    servicer.InstantiateVariable,
                    request_deserializer=geocube_dot_pb_dot_variables__pb2.InstantiateVariableRequest.FromString,
                    response_serializer=geocube_dot_pb_dot_variables__pb2.InstantiateVariableResponse.SerializeToString,
            ),
            'GetVariable': grpc.unary_unary_rpc_method_handler(
                    servicer.GetVariable,
                    request_deserializer=geocube_dot_pb_dot_variables__pb2.GetVariableRequest.FromString,
                    response_serializer=geocube_dot_pb_dot_variables__pb2.GetVariableResponse.SerializeToString,
            ),
            'ListVariables': grpc.unary_stream_rpc_method_handler(
                    servicer.ListVariables,
                    request_deserializer=geocube_dot_pb_dot_variables__pb2.ListVariablesRequest.FromString,
                    response_serializer=geocube_dot_pb_dot_variables__pb2.ListVariablesResponseItem.SerializeToString,
            ),
            'UpdateVariable': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateVariable,
                    request_deserializer=geocube_dot_pb_dot_variables__pb2.UpdateVariableRequest.FromString,
                    response_serializer=geocube_dot_pb_dot_variables__pb2.UpdateVariableResponse.SerializeToString,
            ),
            'UpdateInstance': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateInstance,
                    request_deserializer=geocube_dot_pb_dot_variables__pb2.UpdateInstanceRequest.FromString,
                    response_serializer=geocube_dot_pb_dot_variables__pb2.UpdateInstanceResponse.SerializeToString,
            ),
            'DeleteVariable': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteVariable,
                    request_deserializer=geocube_dot_pb_dot_variables__pb2.DeleteVariableRequest.FromString,
                    response_serializer=geocube_dot_pb_dot_variables__pb2.DeleteVariableResponse.SerializeToString,
            ),
            'DeleteInstance': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteInstance,
                    request_deserializer=geocube_dot_pb_dot_variables__pb2.DeleteInstanceRequest.FromString,
                    response_serializer=geocube_dot_pb_dot_variables__pb2.DeleteInstanceResponse.SerializeToString,
            ),
            'CreatePalette': grpc.unary_unary_rpc_method_handler(
                    servicer.CreatePalette,
                    request_deserializer=geocube_dot_pb_dot_variables__pb2.CreatePaletteRequest.FromString,
                    response_serializer=geocube_dot_pb_dot_variables__pb2.CreatePaletteResponse.SerializeToString,
            ),
            'IndexDatasets': grpc.unary_unary_rpc_method_handler(
                    servicer.IndexDatasets,
                    request_deserializer=geocube_dot_pb_dot_operations__pb2.IndexDatasetsRequest.FromString,
                    response_serializer=geocube_dot_pb_dot_operations__pb2.IndexDatasetsResponse.SerializeToString,
            ),
            'IngestDatasets': grpc.unary_stream_rpc_method_handler(
                    servicer.IngestDatasets,
                    request_deserializer=geocube_dot_pb_dot_operations__pb2.IngestDatasetsRequest.FromString,
                    response_serializer=geocube_dot_pb_dot_operations__pb2.IngestDatasetsResponse.SerializeToString,
            ),
            'ConfigConsolidation': grpc.unary_unary_rpc_method_handler(
                    servicer.ConfigConsolidation,
                    request_deserializer=geocube_dot_pb_dot_operations__pb2.ConfigConsolidationRequest.FromString,
                    response_serializer=geocube_dot_pb_dot_operations__pb2.ConfigConsolidationResponse.SerializeToString,
            ),
            'Consolidate': grpc.unary_unary_rpc_method_handler(
                    servicer.Consolidate,
                    request_deserializer=geocube_dot_pb_dot_operations__pb2.ConsolidateRequest.FromString,
                    response_serializer=geocube_dot_pb_dot_operations__pb2.ConsolidateResponse.SerializeToString,
            ),
            'GetJob': grpc.unary_unary_rpc_method_handler(
                    servicer.GetJob,
                    request_deserializer=geocube_dot_pb_dot_operations__pb2.GetJobRequest.FromString,
                    response_serializer=geocube_dot_pb_dot_operations__pb2.GetJobResponse.SerializeToString,
            ),
            'CleanJobs': grpc.unary_unary_rpc_method_handler(
                    servicer.CleanJobs,
                    request_deserializer=geocube_dot_pb_dot_operations__pb2.CleanJobsRequest.FromString,
                    response_serializer=geocube_dot_pb_dot_operations__pb2.CleanJobsResponse.SerializeToString,
            ),
            'RetryJob': grpc.unary_unary_rpc_method_handler(
                    servicer.RetryJob,
                    request_deserializer=geocube_dot_pb_dot_operations__pb2.RetryJobRequest.FromString,
                    response_serializer=geocube_dot_pb_dot_operations__pb2.RetryJobResponse.SerializeToString,
            ),
            'CancelJob': grpc.unary_unary_rpc_method_handler(
                    servicer.CancelJob,
                    request_deserializer=geocube_dot_pb_dot_operations__pb2.CancelJobRequest.FromString,
                    response_serializer=geocube_dot_pb_dot_operations__pb2.CancelJobResponse.SerializeToString,
            ),
            'GetCube': grpc.unary_stream_rpc_method_handler(
                    servicer.GetCube,
                    request_deserializer=geocube_dot_pb_dot_catalog__pb2.GetCubeRequest.FromString,
                    response_serializer=geocube_dot_pb_dot_catalog__pb2.GetCubeResponse.SerializeToString,
            ),
            'GetXYZTile': grpc.unary_unary_rpc_method_handler(
                    servicer.GetXYZTile,
                    request_deserializer=geocube_dot_pb_dot_catalog__pb2.GetTileRequest.FromString,
                    response_serializer=geocube_dot_pb_dot_catalog__pb2.GetTileResponse.SerializeToString,
            ),
            'CreateLayout': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateLayout,
                    request_deserializer=geocube_dot_pb_dot_layouts__pb2.CreateLayoutRequest.FromString,
                    response_serializer=geocube_dot_pb_dot_layouts__pb2.CreateLayoutResponse.SerializeToString,
            ),
            'TileAOI': grpc.unary_stream_rpc_method_handler(
                    servicer.TileAOI,
                    request_deserializer=geocube_dot_pb_dot_layouts__pb2.TileAOIRequest.FromString,
                    response_serializer=geocube_dot_pb_dot_layouts__pb2.TileAOIResponse.SerializeToString,
            ),
            'Version': grpc.unary_unary_rpc_method_handler(
                    servicer.Version,
                    request_deserializer=geocube_dot_pb_dot_geocube__pb2.GetVersionRequest.FromString,
                    response_serializer=geocube_dot_pb_dot_geocube__pb2.GetVersionResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'geocube.Geocube', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Geocube(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ListRecords(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/geocube.Geocube/ListRecords',
            geocube_dot_pb_dot_records__pb2.ListRecordsRequest.SerializeToString,
            geocube_dot_pb_dot_records__pb2.ListRecordsResponseItem.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CreateRecords(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/geocube.Geocube/CreateRecords',
            geocube_dot_pb_dot_records__pb2.CreateRecordsRequest.SerializeToString,
            geocube_dot_pb_dot_records__pb2.CreateRecordsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DeleteRecords(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/geocube.Geocube/DeleteRecords',
            geocube_dot_pb_dot_records__pb2.DeleteRecordsRequest.SerializeToString,
            geocube_dot_pb_dot_records__pb2.DeleteRecordsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def AddRecordsTags(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/geocube.Geocube/AddRecordsTags',
            geocube_dot_pb_dot_records__pb2.AddRecordsTagsRequest.SerializeToString,
            geocube_dot_pb_dot_records__pb2.AddRecordsTagsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def RemoveRecordsTags(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/geocube.Geocube/RemoveRecordsTags',
            geocube_dot_pb_dot_records__pb2.RemoveRecordsTagsRequest.SerializeToString,
            geocube_dot_pb_dot_records__pb2.RemoveRecordsTagsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CreateAOI(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/geocube.Geocube/CreateAOI',
            geocube_dot_pb_dot_records__pb2.CreateAOIRequest.SerializeToString,
            geocube_dot_pb_dot_records__pb2.CreateAOIResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetAOI(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/geocube.Geocube/GetAOI',
            geocube_dot_pb_dot_records__pb2.GetAOIRequest.SerializeToString,
            geocube_dot_pb_dot_records__pb2.GetAOIResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CreateVariable(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/geocube.Geocube/CreateVariable',
            geocube_dot_pb_dot_variables__pb2.CreateVariableRequest.SerializeToString,
            geocube_dot_pb_dot_variables__pb2.CreateVariableResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def InstantiateVariable(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/geocube.Geocube/InstantiateVariable',
            geocube_dot_pb_dot_variables__pb2.InstantiateVariableRequest.SerializeToString,
            geocube_dot_pb_dot_variables__pb2.InstantiateVariableResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetVariable(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/geocube.Geocube/GetVariable',
            geocube_dot_pb_dot_variables__pb2.GetVariableRequest.SerializeToString,
            geocube_dot_pb_dot_variables__pb2.GetVariableResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ListVariables(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/geocube.Geocube/ListVariables',
            geocube_dot_pb_dot_variables__pb2.ListVariablesRequest.SerializeToString,
            geocube_dot_pb_dot_variables__pb2.ListVariablesResponseItem.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def UpdateVariable(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/geocube.Geocube/UpdateVariable',
            geocube_dot_pb_dot_variables__pb2.UpdateVariableRequest.SerializeToString,
            geocube_dot_pb_dot_variables__pb2.UpdateVariableResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def UpdateInstance(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/geocube.Geocube/UpdateInstance',
            geocube_dot_pb_dot_variables__pb2.UpdateInstanceRequest.SerializeToString,
            geocube_dot_pb_dot_variables__pb2.UpdateInstanceResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DeleteVariable(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/geocube.Geocube/DeleteVariable',
            geocube_dot_pb_dot_variables__pb2.DeleteVariableRequest.SerializeToString,
            geocube_dot_pb_dot_variables__pb2.DeleteVariableResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DeleteInstance(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/geocube.Geocube/DeleteInstance',
            geocube_dot_pb_dot_variables__pb2.DeleteInstanceRequest.SerializeToString,
            geocube_dot_pb_dot_variables__pb2.DeleteInstanceResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CreatePalette(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/geocube.Geocube/CreatePalette',
            geocube_dot_pb_dot_variables__pb2.CreatePaletteRequest.SerializeToString,
            geocube_dot_pb_dot_variables__pb2.CreatePaletteResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def IndexDatasets(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/geocube.Geocube/IndexDatasets',
            geocube_dot_pb_dot_operations__pb2.IndexDatasetsRequest.SerializeToString,
            geocube_dot_pb_dot_operations__pb2.IndexDatasetsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def IngestDatasets(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/geocube.Geocube/IngestDatasets',
            geocube_dot_pb_dot_operations__pb2.IngestDatasetsRequest.SerializeToString,
            geocube_dot_pb_dot_operations__pb2.IngestDatasetsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ConfigConsolidation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/geocube.Geocube/ConfigConsolidation',
            geocube_dot_pb_dot_operations__pb2.ConfigConsolidationRequest.SerializeToString,
            geocube_dot_pb_dot_operations__pb2.ConfigConsolidationResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Consolidate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/geocube.Geocube/Consolidate',
            geocube_dot_pb_dot_operations__pb2.ConsolidateRequest.SerializeToString,
            geocube_dot_pb_dot_operations__pb2.ConsolidateResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetJob(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/geocube.Geocube/GetJob',
            geocube_dot_pb_dot_operations__pb2.GetJobRequest.SerializeToString,
            geocube_dot_pb_dot_operations__pb2.GetJobResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CleanJobs(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/geocube.Geocube/CleanJobs',
            geocube_dot_pb_dot_operations__pb2.CleanJobsRequest.SerializeToString,
            geocube_dot_pb_dot_operations__pb2.CleanJobsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def RetryJob(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/geocube.Geocube/RetryJob',
            geocube_dot_pb_dot_operations__pb2.RetryJobRequest.SerializeToString,
            geocube_dot_pb_dot_operations__pb2.RetryJobResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CancelJob(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/geocube.Geocube/CancelJob',
            geocube_dot_pb_dot_operations__pb2.CancelJobRequest.SerializeToString,
            geocube_dot_pb_dot_operations__pb2.CancelJobResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetCube(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/geocube.Geocube/GetCube',
            geocube_dot_pb_dot_catalog__pb2.GetCubeRequest.SerializeToString,
            geocube_dot_pb_dot_catalog__pb2.GetCubeResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetXYZTile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/geocube.Geocube/GetXYZTile',
            geocube_dot_pb_dot_catalog__pb2.GetTileRequest.SerializeToString,
            geocube_dot_pb_dot_catalog__pb2.GetTileResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CreateLayout(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/geocube.Geocube/CreateLayout',
            geocube_dot_pb_dot_layouts__pb2.CreateLayoutRequest.SerializeToString,
            geocube_dot_pb_dot_layouts__pb2.CreateLayoutResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def TileAOI(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/geocube.Geocube/TileAOI',
            geocube_dot_pb_dot_layouts__pb2.TileAOIRequest.SerializeToString,
            geocube_dot_pb_dot_layouts__pb2.TileAOIResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Version(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/geocube.Geocube/Version',
            geocube_dot_pb_dot_geocube__pb2.GetVersionRequest.SerializeToString,
            geocube_dot_pb_dot_geocube__pb2.GetVersionResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
