# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: geocube/pb/layouts.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from geocube.pb import records_pb2 as geocube_dot_pb_dot_records__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='geocube/pb/layouts.proto',
  package='geocube',
  syntax='proto3',
  serialized_options=b'Z\014./pb;geocube',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x18geocube/pb/layouts.proto\x12\x07geocube\x1a\x18geocube/pb/records.proto\"%\n\x04Size\x12\r\n\x05width\x18\x01 \x01(\x05\x12\x0e\n\x06height\x18\x02 \x01(\x05\"P\n\x0cGeoTransform\x12\t\n\x01\x61\x18\x01 \x01(\x01\x12\t\n\x01\x62\x18\x02 \x01(\x01\x12\t\n\x01\x63\x18\x03 \x01(\x01\x12\t\n\x01\x64\x18\x04 \x01(\x01\x12\t\n\x01\x65\x18\x05 \x01(\x01\x12\t\n\x01\x66\x18\x06 \x01(\x01\"]\n\x04Tile\x12(\n\ttransform\x18\x01 \x01(\x0b\x32\x15.geocube.GeoTransform\x12\x1e\n\x07size_px\x18\x02 \x01(\x0b\x32\r.geocube.Size\x12\x0b\n\x03\x63rs\x18\x03 \x01(\t\"\xe6\x01\n\tNewLayout\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x12\n\ngrid_flags\x18\x02 \x03(\t\x12?\n\x0fgrid_parameters\x18\x03 \x03(\x0b\x32&.geocube.NewLayout.GridParametersEntry\x12\x14\n\x0c\x62lock_x_size\x18\x04 \x01(\x03\x12\x14\n\x0c\x62lock_y_size\x18\x05 \x01(\x03\x12\x13\n\x0bmax_records\x18\x06 \x01(\x03\x1a\x35\n\x13GridParametersEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"9\n\x13\x43reateLayoutRequest\x12\"\n\x06layout\x18\x01 \x01(\x0b\x32\x12.geocube.NewLayout\"\"\n\x14\x43reateLayoutResponse\x12\n\n\x02id\x18\x01 \x01(\t\"l\n\x0eTileAOIRequest\x12\x19\n\x03\x61oi\x18\x01 \x01(\x0b\x32\x0c.geocube.AOI\x12\x0b\n\x03\x63rs\x18\x02 \x01(\t\x12\x12\n\nresolution\x18\x03 \x01(\x02\x12\x1e\n\x07size_px\x18\x04 \x01(\x0b\x32\r.geocube.Size\"/\n\x0fTileAOIResponse\x12\x1c\n\x05tiles\x18\x01 \x03(\x0b\x32\r.geocube.TileB\x0eZ\x0c./pb;geocubeb\x06proto3'
  ,
  dependencies=[geocube_dot_pb_dot_records__pb2.DESCRIPTOR,])




_SIZE = _descriptor.Descriptor(
  name='Size',
  full_name='geocube.Size',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='width', full_name='geocube.Size.width', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='height', full_name='geocube.Size.height', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=63,
  serialized_end=100,
)


_GEOTRANSFORM = _descriptor.Descriptor(
  name='GeoTransform',
  full_name='geocube.GeoTransform',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='a', full_name='geocube.GeoTransform.a', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='b', full_name='geocube.GeoTransform.b', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='c', full_name='geocube.GeoTransform.c', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='d', full_name='geocube.GeoTransform.d', index=3,
      number=4, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='e', full_name='geocube.GeoTransform.e', index=4,
      number=5, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='f', full_name='geocube.GeoTransform.f', index=5,
      number=6, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=102,
  serialized_end=182,
)


_TILE = _descriptor.Descriptor(
  name='Tile',
  full_name='geocube.Tile',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='transform', full_name='geocube.Tile.transform', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='size_px', full_name='geocube.Tile.size_px', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='crs', full_name='geocube.Tile.crs', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=184,
  serialized_end=277,
)


_NEWLAYOUT_GRIDPARAMETERSENTRY = _descriptor.Descriptor(
  name='GridParametersEntry',
  full_name='geocube.NewLayout.GridParametersEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='geocube.NewLayout.GridParametersEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='value', full_name='geocube.NewLayout.GridParametersEntry.value', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=b'8\001',
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=457,
  serialized_end=510,
)

_NEWLAYOUT = _descriptor.Descriptor(
  name='NewLayout',
  full_name='geocube.NewLayout',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='geocube.NewLayout.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='grid_flags', full_name='geocube.NewLayout.grid_flags', index=1,
      number=2, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='grid_parameters', full_name='geocube.NewLayout.grid_parameters', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='block_x_size', full_name='geocube.NewLayout.block_x_size', index=3,
      number=4, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='block_y_size', full_name='geocube.NewLayout.block_y_size', index=4,
      number=5, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='max_records', full_name='geocube.NewLayout.max_records', index=5,
      number=6, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_NEWLAYOUT_GRIDPARAMETERSENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=280,
  serialized_end=510,
)


_CREATELAYOUTREQUEST = _descriptor.Descriptor(
  name='CreateLayoutRequest',
  full_name='geocube.CreateLayoutRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='layout', full_name='geocube.CreateLayoutRequest.layout', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=512,
  serialized_end=569,
)


_CREATELAYOUTRESPONSE = _descriptor.Descriptor(
  name='CreateLayoutResponse',
  full_name='geocube.CreateLayoutResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='geocube.CreateLayoutResponse.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=571,
  serialized_end=605,
)


_TILEAOIREQUEST = _descriptor.Descriptor(
  name='TileAOIRequest',
  full_name='geocube.TileAOIRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='aoi', full_name='geocube.TileAOIRequest.aoi', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='crs', full_name='geocube.TileAOIRequest.crs', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='resolution', full_name='geocube.TileAOIRequest.resolution', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='size_px', full_name='geocube.TileAOIRequest.size_px', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=607,
  serialized_end=715,
)


_TILEAOIRESPONSE = _descriptor.Descriptor(
  name='TileAOIResponse',
  full_name='geocube.TileAOIResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='tiles', full_name='geocube.TileAOIResponse.tiles', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=717,
  serialized_end=764,
)

_TILE.fields_by_name['transform'].message_type = _GEOTRANSFORM
_TILE.fields_by_name['size_px'].message_type = _SIZE
_NEWLAYOUT_GRIDPARAMETERSENTRY.containing_type = _NEWLAYOUT
_NEWLAYOUT.fields_by_name['grid_parameters'].message_type = _NEWLAYOUT_GRIDPARAMETERSENTRY
_CREATELAYOUTREQUEST.fields_by_name['layout'].message_type = _NEWLAYOUT
_TILEAOIREQUEST.fields_by_name['aoi'].message_type = geocube_dot_pb_dot_records__pb2._AOI
_TILEAOIREQUEST.fields_by_name['size_px'].message_type = _SIZE
_TILEAOIRESPONSE.fields_by_name['tiles'].message_type = _TILE
DESCRIPTOR.message_types_by_name['Size'] = _SIZE
DESCRIPTOR.message_types_by_name['GeoTransform'] = _GEOTRANSFORM
DESCRIPTOR.message_types_by_name['Tile'] = _TILE
DESCRIPTOR.message_types_by_name['NewLayout'] = _NEWLAYOUT
DESCRIPTOR.message_types_by_name['CreateLayoutRequest'] = _CREATELAYOUTREQUEST
DESCRIPTOR.message_types_by_name['CreateLayoutResponse'] = _CREATELAYOUTRESPONSE
DESCRIPTOR.message_types_by_name['TileAOIRequest'] = _TILEAOIREQUEST
DESCRIPTOR.message_types_by_name['TileAOIResponse'] = _TILEAOIRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Size = _reflection.GeneratedProtocolMessageType('Size', (_message.Message,), {
  'DESCRIPTOR' : _SIZE,
  '__module__' : 'geocube.pb.layouts_pb2'
  # @@protoc_insertion_point(class_scope:geocube.Size)
  })
_sym_db.RegisterMessage(Size)

GeoTransform = _reflection.GeneratedProtocolMessageType('GeoTransform', (_message.Message,), {
  'DESCRIPTOR' : _GEOTRANSFORM,
  '__module__' : 'geocube.pb.layouts_pb2'
  # @@protoc_insertion_point(class_scope:geocube.GeoTransform)
  })
_sym_db.RegisterMessage(GeoTransform)

Tile = _reflection.GeneratedProtocolMessageType('Tile', (_message.Message,), {
  'DESCRIPTOR' : _TILE,
  '__module__' : 'geocube.pb.layouts_pb2'
  # @@protoc_insertion_point(class_scope:geocube.Tile)
  })
_sym_db.RegisterMessage(Tile)

NewLayout = _reflection.GeneratedProtocolMessageType('NewLayout', (_message.Message,), {

  'GridParametersEntry' : _reflection.GeneratedProtocolMessageType('GridParametersEntry', (_message.Message,), {
    'DESCRIPTOR' : _NEWLAYOUT_GRIDPARAMETERSENTRY,
    '__module__' : 'geocube.pb.layouts_pb2'
    # @@protoc_insertion_point(class_scope:geocube.NewLayout.GridParametersEntry)
    })
  ,
  'DESCRIPTOR' : _NEWLAYOUT,
  '__module__' : 'geocube.pb.layouts_pb2'
  # @@protoc_insertion_point(class_scope:geocube.NewLayout)
  })
_sym_db.RegisterMessage(NewLayout)
_sym_db.RegisterMessage(NewLayout.GridParametersEntry)

CreateLayoutRequest = _reflection.GeneratedProtocolMessageType('CreateLayoutRequest', (_message.Message,), {
  'DESCRIPTOR' : _CREATELAYOUTREQUEST,
  '__module__' : 'geocube.pb.layouts_pb2'
  # @@protoc_insertion_point(class_scope:geocube.CreateLayoutRequest)
  })
_sym_db.RegisterMessage(CreateLayoutRequest)

CreateLayoutResponse = _reflection.GeneratedProtocolMessageType('CreateLayoutResponse', (_message.Message,), {
  'DESCRIPTOR' : _CREATELAYOUTRESPONSE,
  '__module__' : 'geocube.pb.layouts_pb2'
  # @@protoc_insertion_point(class_scope:geocube.CreateLayoutResponse)
  })
_sym_db.RegisterMessage(CreateLayoutResponse)

TileAOIRequest = _reflection.GeneratedProtocolMessageType('TileAOIRequest', (_message.Message,), {
  'DESCRIPTOR' : _TILEAOIREQUEST,
  '__module__' : 'geocube.pb.layouts_pb2'
  # @@protoc_insertion_point(class_scope:geocube.TileAOIRequest)
  })
_sym_db.RegisterMessage(TileAOIRequest)

TileAOIResponse = _reflection.GeneratedProtocolMessageType('TileAOIResponse', (_message.Message,), {
  'DESCRIPTOR' : _TILEAOIRESPONSE,
  '__module__' : 'geocube.pb.layouts_pb2'
  # @@protoc_insertion_point(class_scope:geocube.TileAOIResponse)
  })
_sym_db.RegisterMessage(TileAOIResponse)


DESCRIPTOR._options = None
_NEWLAYOUT_GRIDPARAMETERSENTRY._options = None
# @@protoc_insertion_point(module_scope)
