ARG GDALVERSION=3.8.4
ARG GEOCUBEVERSION=v1.0.3
ARG GEOCUBECLIENTVERSION=v1.0.4
ARG GO_VERSION=1.23.2

FROM ubuntu:noble AS builder
ARG GDALVERSION
ARG GEOCUBEVERSION
ARG GO_VERSION

ENV DEBIAN_FRONTEND=noninteractive
ENV TZ=Etc/UTC

RUN apt update \
    && apt install -y \
        build-essential \
        cmake \
        curl \
        git \
        g++ \
        libboost-filesystem-dev \
        libcurl4-openssl-dev \
        libdeflate-dev \
        libjpeg-dev \
        liblerc-dev \
        libproj-dev \
        libwebp-dev \
        libtiff-dev \
        libzstd-dev \
        pkg-config \
    && rm -rf /var/lib/apt/lists/* \
    && apt autoremove -y \
    && apt clean -y

WORKDIR /build

RUN mkdir gdal && cd gdal &&\
    curl -sL https://github.com/OSGeo/gdal/releases/download/v$GDALVERSION/gdal-$GDALVERSION.tar.gz | tar xz --strip-components 1 &&\
	mkdir -p build && cd build && \
    cmake .. \
        -DBUILD_TESTING=OFF \
        -DCMAKE_BUILD_TYPE=Release \
        -DOGR_BUILD_OPTIONAL_DRIVERS=OFF \
        -DGDAL_BUILD_OPTIONAL_DRIVERS=OFF \
        -DGDAL_USE_CURL=ON \
        -DGDAL_USE_OPENCL=OFF \
        -DGDAL_USE_EXPAT=OFF \
        -DGDAL_USE_LIBXML2=OFF \
        -DGDAL_USE_SQLITE3=OFF \
        -DGDAL_USE_XERCESC=OFF \
        -DGDAL_USE_TIFF_INTERNAL=ON \
        -DGDAL_USE_GEOTIFF_INTERNAL=ON \
        -DGDAL_ENABLE_DRIVER_WEBP=ON \
        -DGDAL_ENABLE_DRIVER_JPEG=ON \
        -DGDAL_USE_LERC=ON \
        -DGDAL_USE_ZSTD=ON && \
    cmake --build . --target install && \
    ldconfig /usr/local/lib &&\
    cd /build && rm -rf gdal
ENV PKG_CONFIG_PATH=/usr/local/lib/pkgconfig/

RUN curl -fsL "https://golang.org/dl/go${GO_VERSION}.linux-amd64.tar.gz" | tar -C /usr/local -xzf -
ENV PATH="/usr/local/go/bin:${PATH}"

RUN git clone -b $GEOCUBEVERSION --depth 1 https://github.com/airbusgeo/geocube.git \
    && cd geocube/cmd/downloader \
    && go build -ldflags="-s -w" \
    && mv downloader /build/ \
    && cd /build && rm -rf geocube

FROM ubuntu:noble
ARG GDALVERSION
ARG GEOCUBECLIENTVERSION

ENV GRPC_ENABLE_FORK_SUPPORT=1
ENV TINI_VERSION=v0.19.0

COPY --from=builder /usr/local/lib /usr/local/lib
COPY --from=builder /usr/local/share /usr/local/share
COPY --from=builder /usr/local/bin/ /usr/local/bin/
COPY --from=builder /usr/local/include /usr/local/include
COPY --from=builder /build/downloader /usr/bin/downloader
COPY docker/prepare_downloader.sh /usr/bin/prepare_downloader.sh

RUN apt update \
    && apt install -y --no-install-recommends \
        g++ \
        git \
        python3-pip \
        python3-setuptools \
        python3-dev \
        python3-numpy \
        pkg-config \
        libcurl4 \
        libjpeg62 \
        libdeflate0 \
        liblerc4 \
        libwebp7 \
        libzstd1 \
        libproj25 \
        libtiff6 \
    && ln -s /usr/bin/python3 /usr/bin/python \
    && python3 -m pip install --break-system-packages \
        gcloud \
        git+https://github.com/airbusgeo/geocube-client-python.git@$GEOCUBECLIENTVERSION \
        GDAL==$GDALVERSION \
    && apt remove -y git g++ python3-dev --purge \
    && rm -rf /var/lib/apt/lists/* \
    && apt autoremove -y \
    && apt clean -y

# Test critical imports (move to separate layer for better caching)
RUN python -c "from osgeo import gdal, gdal_array; print('GDAL version:', gdal.__version__);"

ENV GEOCUBE_DOWNLOADER=127.0.0.1:8083

# Add Tini
ADD https://github.com/krallin/tini/releases/download/${TINI_VERSION}/tini /tini
RUN chmod +x /tini && chmod +x /usr/bin/prepare_downloader.sh && mkdir /var/log/container
ENTRYPOINT ["/tini", "-g", "--", "/usr/bin/prepare_downloader.sh"]
